backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    path: "{{slug}}/index"
    create: true
    extension: "md"
    frontmatter_format: "yaml"
    media_folder: ""
    public_folder: ""
    format: "yaml"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Last Modified",
          name: "lastmod",
          widget: "datetime",
          required: false,
        }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Image", name: "image", widget: "image", required: false }
      - {
          label: "Image Big",
          name: "imageBig",
          widget: "image",
          required: false,
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          summary: "{{fields.category}}",
          field: { label: "Category", name: "category", widget: "string" },
        }
      - {
          label: "Medium Link",
          name: "mediumLink",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
