backend:
  name: git-gateway
  branch: main

media_folder: "static/images" # Folder for uploaded files
public_folder: "images"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts"
    folder: "content/posts"
    path: "{{slug}}/index"
    media_folder: "" # Images go into the same folder as the post
    public_folder: ""
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Last Modified",
          name: "lastmod",
          widget: "datetime",
          required: false,
        }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - {
          label: "Image Big",
          name: "ImageBig",
          widget: "image",
          required: false,
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          field: { label: "Category", name: "category", widget: "string" },
        }
      - {
          label: "Medium Link",
          name: "mediumLink",
          widget: "string",
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          hint: "Write your article here",
        }
